[theme]

# Primary accent for interactive elements
primaryColor = '#7792E3'

# Background color for the main content area
backgroundColor = '#B9F1C0'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#273346'

# Color used for almost all text
textColor = '#981eb5'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"